### ISSUE TITLE
Folders cleanup after refactoring

### ISSUE THREAD

**Issue by puzrin** [Ralim/usb-pd#7]
I'd suggest more recogniseable structure of files:

```
/src/

  - int_n.cpp
  - policy_engine.cpp
  - policy_engine_states.cpp
  - driver_fusb302b.cpp

/include/

  headers
```

Also consider reduce amount of header files. IMO those are too much without need.

**Comment by Ralim** [comment]
Hi,

There is some logic in the current layout:

- fusb is in its own folder as that allows for drivers for future devices that are not the FUSB302 to be kept in their own folders
- using lib and tests to keep these entirely separate
- As FUSB will be kept separate, it feels better to keep the core logic in logic rather than src, since src is exceptionally general and looks like a filler folder that most projects use.


I agree `pdb_conf` will go, the others are split for a reason.

**Comment by puzrin** [comment]
IMO folder's struct has "history", not actual at current moment.

First of all, as "stupid user", i need to include this dependency to "my project" without pain. If library has `src/` + `include/` folders, PlatformIO and Arduino should understand that by default (even without extra configs).

> using lib and tests to keep these entirely separate

`test/` will stay in root. I mean only `lib/` should be reorganized, because it's too nested without need, and a bit unusual (`include` + `src` are more common/recognizable)

> As FUSB will be kept separate, it feels better to keep the core logic in logic rather than src, since src is exceptionally general and looks like a filler folder that most projects use.

Just use `driver_` prefix or suffix in file name. Let's be realistic. Here is only one driver `.c` file (for fusb302). May be... if miracle happens... second file fill be added for stm32gXX (but i'm a bit sceptical about that). 2 files max, not more.

Subfolders are nice when project have zillions of files. But for 4-5 files subfolders are annoying because prevent to see all at once.

**Comment by Ralim** [comment]
Less likely to be the stm32xxxx driver and more likely to be the NXP or TI phy ic's added at some point (when need arises).

Given the project uses cmake, it is trivial to add into any cmake build system(`add_library`).
If your using a makefile based project just add its source to your normal pickup system.
If your building a library for Arduino or other externally controlled systems, I assume they have a relatively simple way for you to indicate to them how to build the code into a library and link it into the project, or include them in their build plan?

Honestly, haven't used platformIO since I first looked at it and it was very web focused which ruled it out in seconds.

What ancient editor are you using that doesn't collapse out extra folders in the path? 😂

**Comment by puzrin** [comment]
> If your building a library for Arduino or other externally controlled systems, I assume they have a relatively simple way for you to indicate to them how to build the code into a library and link it into the project, or include them in their build plan?

Sure, it's possible to add configs for arduino & pio. But if project organized according to "common conventions", it will work without configs.

> What ancient editor are you using that doesn't collapse out extra folders in the path? joy

That's not about "possibility", that's about "usability". Every extra action => decrease usability.

**Comment by Ralim** [comment]
I reshuffled to match pitchfork, should work for you now?

I have nothing to test Arduino and co on, so let me know if that folder layout works for you :)
